create schema if not exists login;

CREATE TABLE userCredentials(
	id INTEGER generated by default as identity start with 1,
    userName VARCHAR(25) NOT NULL,
    loginpassword VARCHAR(25) NOT NULL,
    PRIMARY KEY (id, userName)
);

Insert into userCredentials (userName, loginpassword)
	values('admin','secret'),('guest','password'),('moderator','123'),('ghost','password');
